# Generated by Django 4.0 on 2022-09-13 08:49

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='key')),
                ('value', models.TextField(blank=True, verbose_name='value')),
                ('value_en', models.TextField(blank=True, null=True, verbose_name='value')),
                ('value_de', models.TextField(blank=True, null=True, verbose_name='value')),
            ],
            options={
                'verbose_name': 'translation',
                'verbose_name_plural': 'translations',
                'ordering': ('key',),
            },
        ),
    ]
