# Generated by Django 4.0 on 2022-09-13 08:55
import json
import os

from django.db import migrations


def load_initial_translations(apps, schema_editor):
    dir_path = os.path.dirname(os.path.realpath(__file__))
    en_json_file = open(os.path.join(dir_path, 'initial_translations', 'en.json'), encoding='utf-8')
    de_json_file = open(os.path.join(dir_path, 'initial_translations', 'de.json'), encoding='utf-8')
    en_json = json.load(en_json_file)
    de_json = json.load(de_json_file)

    Translation = apps.get_model('translation', 'Translation')
    for k, v in en_json.items():
        de_value = de_json.get(k)
        translation = Translation.objects.create(
            key=k,
            value_en=v,
        )
        if de_value:
            translation.value_de = de_value
        translation.save()
    en_json_file.close()
    de_json_file.close()


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_translations),
    ]
