# Generated by Django 4.0 on 2023-06-06 13:30
from django.core.management import call_command
from django.db import migrations


def import_interface_template(apps, schema_editor):
    call_command('loaddata', 'admin_interface_theme_django.json')
    call_command('loaddata', 'admin_interface_theme_bootstrap.json')
    call_command('loaddata', 'admin_interface_theme_foundation.json')
    call_command('loaddata', 'admin_interface_theme_uswds.json')


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(import_interface_template, reverse_code=migrations.RunPython.noop),
    ]
