# Generated by Django 4.2.3 on 2024-07-02 16:17

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailBindr',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.TextField(verbose_name='To')),
                ('variables', models.JSONField(blank=True, null=True, verbose_name='Variables')),
                ('bcc', models.TextField(blank=True, verbose_name='bcc')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is sent')),
                ('response', models.TextField(blank=True, null=True, verbose_name='response')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Error')),
            ],
            options={
                'verbose_name': 'Mail Binder',
                'verbose_name_plural': 'Mail Binders',
                'ordering': ('-created',),
            },
        ),
    ]
