# Generated by Django 4.2.3 on 2024-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_mailbindr'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbindr',
            name='html_body',
            field=models.TextField(blank=True, null=True, verbose_name='html body'),
        ),
    ]
