version: '3'
services:
  redis:
    image: redis:7.4-alpine

  mjml:
    image: liminspace/mjml-tcpserver:1.0

  database:
    image: postgres:17.2
    restart: always
    env_file: test.env

  app:
    image: "${CI_PIPELINE_ID}/${CONTEXT}:${CI_COMMIT_REF_NAME}"
    env_file: test.env
    volumes:
      - ./htmlcov:/app/htmlcov
    depends_on:
      - database
      - redis
      - mjml
